### ISSUE TITLE
swiftmailer.mailer.transport.fl_gmail.swift_transport

### ISSUE THREAD

**Issue by grekpg** [fourlabsldn/GmailBundle#2]
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                                                                          
  The service "swiftmailer.mailer.transport.fl_gmail.swift_transport" has a dependency on a non-existent service "swiftmailer.mailer.fl_gmail_api_mailer.transport.eventdispatcher".

**Comment by galeaspablo** [comment]
Make sure you have a swiftmailer configuration for that particular name

``` yaml
# app/config/config.yml
swiftmailer:
    default_mailer: general_mailer
    mailers:
        general_mailer:
            transport: "%mailer_transport%"
            host:      "%mailer_host%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            spool:     { type: memory }
        fl_gmail_api_mailer:
            transport: fl_gmail.swift_transport
```

Also see http://symfony.com/doc/current/reference/configuration/swiftmailer.html#using-multiple-mailers
